
name: Run Unit Tests
on: [push, pull_request]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: yarn install
      run: yarn install

    - name: run lint
      run: yarn run eslint

    - name: yarn run test-ci
      run: yarn run test-ci
